### ISSUE TITLE
Feat:Implementing the GSoC Page

### ISSUE THREAD

**Issue by Saumya-28** [andoriyaprashant/OpSo#44]
### Describe the feature

This Projects requires the implementation of the GSoC Page for further user engagement and content to deliver.

### Add ScreenShots

<img src="https://github.com/andoriyaprashant/OpSo/assets/98171392/0219aaad-4c11-4377-8f1b-73f11b1c69b5" width="200" height="400">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SumitPareek2401** [comment]
There are a lot of projects in the GSoC of many different organizations. It requires a lot of time to collect all the data. Can we divide this task according to year (i.e. 2024, 2023, 2022) to complete it together or otherwise @Saumya-28  can you please tell us the deadline in which you can complete it. So that everyone can get a chance to contribute.

**Comment by Saumya-28** [comment]
Hi @SumitPareek2401 ,
I'm currently working on it and will create a pr asap..but I suppose there wont be any topic as such to contribute for the enhancement of the GSoC page..how about you consider to work on the GSoD one as it has not been implemented yet.

**Comment by SumitPareek2401** [comment]
Okay I will open the issue on the GSoD page.
